# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
builds:
- id: terraform-provider-atlas
  env:
    # goreleaser does not work with CGO, it could also complicate
    # usage by users in CI/CD systems like Terraform Cloud where
    # they are unable to install libraries.
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
  binary: '{{ .ProjectName }}_v{{ .Version }}'
  hooks:
    post:
      - ./scripts/atlas.sh {{ .Os }}-{{ .Arch }} {{ dir .Path }}/atlas{{ .Ext }}
archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  format: zip
  files:
    - LICENSE
    - README.md
    - src: 'dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/atlas*'
      strip_parent: true
      info:
        mode: 0755
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
      glob: 'terraform-registry-manifest.json'
signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you 
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  prerelease: auto
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  draft: true
  make_latest: false
changelog:
  skip: true
